
[env]
TERM = "xterm-256color"

[font]
# scale_with_dpi = true
size = 20

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 5

[font.italic]
family = "MesloLGS Nerd Font"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 10

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Minus"
mods = "Command|Shift"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0

[general]
import = ["~/.config/alacritty/gruvbox.toml"]

