color_theme = "gruvbox_dark"
theme_background = true
truecolor = true
force_tty = false
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
vim_keys = true
update_ms = 1000
save_config_on_exit = false
