## Gruvbox Dark Hard

set-environment -g FZF_DEFAULT_OPTS "--color=dark,bg:#1d2021,bg+:#504945,fg:#ebdbb2,fg+:#ebdbb2,hl:#fabd2f,hl+:#fe8019,info:#83a598,prompt:#fe8019,pointer:#fb4934,marker:#8ec07c,spinner:#83a598,header:#928374,border:#504945 --bind=ctrl-a:select-all"
set-environment -g LG_CONFIG_FILE "$HOME/.config/lazygit/config.yml,$HOME/.config/lazygit/themes/gruvbox-dark-hard.yml"
set-environment -g DELTA_FEATURES "gruvbox-dark-hard"

set -g @theme-status-bg "#1d2021"
set -g @theme-status-fg "#ebdbb2"
set -g @theme-window-bg "#282828"
set -g @theme-window-fg "#3c3836"
set -g @theme-window-activity-bg "#282828"
set -g @theme-window-activity-fg "#a89984"
set -g @theme-window-current-bg "#fb4934"
set -g @theme-window-current-fg "#3c3836"
set -g @theme-window-bell-bg "#fb4934"
set -g @theme-window-bell-fg "#1d2021"
set -g @theme-pane-active-border "#282828"
set -g @theme-pane-border "#282828"
set -g @theme-popup-border "#504945"
set -g @theme-message-bg "#504945"
set -g @theme-message-fg "#ebdbb2"
set -g @theme-display-panes-active "#d5c4a1"
set -g @theme-display-panes "#3c3836"
set -g @theme-clock "#83a598"
set -g @theme-session-bg "#fe8019"
set -g @theme-session-fg "#1d2021"
set -g @theme-status-right-bg "#a89984"
set -g @theme-status-right-fg "#1d2021"
set -g @theme-window-format-bg "#1d2021"
set -g @theme-window-format-fg "#928374"
set -g @theme-window-current-format-bg "#928374"
set -g @theme-window-current-format-fg "#1d2021"
