[tools]
"github:agavra/tuicr" = "v0.24.0"
"github:ankitpokhrel/jira-cli" = "latest"
"github:asciinema/asciinema" = "latest"
"github:Skyscanner/turbolift" = "latest"
bat = "latest"
fd = "latest"
gh = "latest"
hyperfine = "latest"
jq = "latest"
lazydocker = "0.25.2"
lazygit = "0.64.1"
opencode = "latest"
ripgrep = "latest"
shfmt = "latest"
uv = "0.12.6"
zls = "0.16.0"
