set -gF status-style "bg=#{@theme-status-bg},fg=#{@theme-status-fg}"

setw -gF window-status-style "bg=#{@theme-window-bg},fg=#{@theme-window-fg}"
setw -gF window-status-activity-style "bg=#{@theme-window-activity-bg},fg=#{@theme-window-activity-fg}"
setw -gF window-status-current-style "bg=#{@theme-window-current-bg},fg=#{@theme-window-current-fg}"
setw -gF window-status-bell-style "bg=#{@theme-window-bell-bg},fg=#{@theme-window-bell-fg}"

set -gF pane-active-border-style "fg=#{@theme-pane-active-border}"
set -gF pane-border-style "fg=#{@theme-pane-border}"
set -gF popup-border-style "fg=#{@theme-popup-border}"

set -gF message-style "bg=#{@theme-message-bg},fg=#{@theme-message-fg}"
set -gF message-command-style "bg=#{@theme-message-bg},fg=#{@theme-message-fg}"
set -gF display-panes-active-colour "#{@theme-display-panes-active}"
set -gF display-panes-colour "#{@theme-display-panes}"
setw -gF clock-mode-colour "#{@theme-clock}"

set -g status-left "#[fg=#{@theme-session-fg},bg=#{@theme-session-bg}] #S "
set -g status-right "#[fg=#{@theme-status-right-fg},bg=#{@theme-status-right-bg},nobold,nounderscore,noitalics] #(~/tmux_battery.sh)  %a, %b %d  %H:%M "

setw -g window-status-format "#[fg=#{@theme-window-format-fg},bg=#{@theme-window-format-bg}] #I #W "
setw -g window-status-current-format "#[fg=#{@theme-window-current-format-fg},bg=#{@theme-window-current-format-bg},nobold,nounderscore,noitalics] #I #W "
