#!/usr/bin/env bash

set -eu

if [ -f ".git/info/exclude" ]; then
    cat <<EOF >>.git/info/exclude
.claude
.dfftignore
.fdignore
.plans
.research
.references
.instructions
.opencode
ARCHITECTURE.md
CLAUDE.md
AGENTS.md
PLAN.md
TASK.md
EOF
fi

if [ ! -f ".fdignore" ]; then
    touch .fdignore
    cat <<EOF >.fdignore
!.fdignore
!.claude
!.dfftignore
!.fdignore
!.plans
!.research
!.references
!.instructions
!.opencode
!ARCHITECTURE.md
!CLAUDE.md
!AGENTS.md
!PLAN.md
!TASK.md
EOF
else
    cat <<EOF >>.fdignore
!.claude
!.dfftignore
!.fdignore
!.plans
!.research
!.references
!.instructions
!.opencode
!ARCHITECTURE.md
!CLAUDE.md
!AGENTS.md
!PLAN.md
!TASK.md
EOF
fi

touch .dfftignore
cat <<EOF >>.dfftignore
.DS_Store
.git
.plans
EOF
