#!/usr/bin/env bash

set -eu

mkdir -p .references

if [ -f ".git/info/exclude" ]; then
    cat <<EOF >>.git/info/exclude
.fdignore
.opencode
.context
.references
EOF
fi

if [ ! -f ".fdignore" ]; then
    touch .fdignore
fi

cat <<EOF >>.fdignore
!.fdignore
!.opencode
!.context
!.references
.context/**/old
EOF
