#!/usr/bin/env bash

set -e
set -o pipefail

commands=("aws" "jq")

for cmd in "${commands[@]}"; do
    if ! command -v $cmd >/dev/null 2>&1; then
        echo "This utility requires \"$cmd\" to be installed"
        exit 1
    fi
done

if [ $# -ne 1 ]; then
    echo "Usage: $0 <role-arn>" >&2
    exit 1
fi

ROLE_ARN="$1"
OUT=$(AWS_PAGER="" aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name session)

key_id=$(echo $OUT | jq -r '.Credentials''.AccessKeyId')
secret_access_key=$(echo $OUT | jq -r '.Credentials''.SecretAccessKey')
session_token=$(echo $OUT | jq -r '.Credentials''.SessionToken')

echo "export AWS_ACCESS_KEY_ID='${key_id}'"
echo "export AWS_SECRET_ACCESS_KEY='${secret_access_key}'"
echo "export AWS_SESSION_TOKEN='${session_token}'"
