#!/usr/bin/env bash

set -e
set -o pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <repo>" >&2
    exit 1
fi

gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "/repos/${1}/contributors?per_page=10" \
    --jq '.[].login' | sed 's/^/https:\/\/github.com\//' | xargs open
