#!/usr/bin/env bash

set -e
set -o pipefail

if [ $# -lt 4 ]; then
    echo "Usage: $0 <owner> <label> <desc> <color> [repo ...]"
    exit 1
fi

owner=$1
label=$2
desc=$3
color=$4

if [ $# -gt 4 ]; then
    repos=$(printf '%s\n' "${@:5}")
else
    repos=$(gh repo list "$owner" --limit 100 --source --no-archived --json name --jq '.[].name')
fi

echo -e "repos:\n$(echo $repos | xargs)"

echo ""
echo "gh label create \"$label\" --repo \"$owner/REPO\" --color \"$color\" --description \"$desc\" --force"
echo ""

gum confirm "proceed?"

while IFS= read -r repo; do
    gh label create "$label" --repo "$owner/$repo" --color "$color" --description "$desc" --force
done <<<"$repos"
