#!/usr/bin/env bash

recipes=$(just --list --list-heading='' --list-prefix='' --no-aliases) || exit $?

recipe=$(printf '%s\n' "$recipes" | awk 'NF { print $1 }' | fzf --height=15 --layout=reverse --style=minimal)
exit_code=$?

if [[ $exit_code -eq 130 ]]; then
    exit 0
fi

just "$recipe"

jl
