#!/usr/bin/env bash

output="$(gh workflow run mrj.yml --repo dhth/deps)"
printf '%s\n' "$output"
while IFS= read -r line; do
    [[ "$line" == https://github.com/* ]] && open "$line" && break
done <<<"$output"
