#!/usr/bin/env bash

set -e

GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m'

usage() {
    echo "Usage: semdiff [-p value] argument1 argument2"
    exit 1
}

if [ "$#" -lt 2 ] || [ "$#" -gt 4 ]; then
    usage
fi

pattern=""

while getopts ":p:" opt; do
    case ${opt} in
    p)
        pattern="$OPTARG"
        ;;
    \?)
        echo "Invalid option: -$OPTARG" 1>&2
        usage
        ;;
    :)
        echo "Option -$OPTARG requires an argument" 1>&2
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

start="$1"
end="$2"

start_file="/tmp/semdiff_$start.txt"
end_file="/tmp/semdiff_$end.txt"

# echo -e "${ORANGE}git checkout $start${NC}"
git checkout "$start" >/dev/null 2>&1
echo -e "${GREEN}git ls-files "$pattern" | dstll -plain=true > $start_file${NC}"
git ls-files "$pattern" | dstll -plain=true >"$start_file"

echo -e ""

# echo -e "${ORANGE}git checkout $end${NC}"
git checkout "$end" >/dev/null 2>&1
echo -e "${GREEN}git ls-files "$pattern" | dstll -plain=true > $end_file${NC}"
git ls-files "$pattern" | dstll -plain=true >"$end_file"

echo -e "${ORANGE}git diff --ignore-space-at-eol --no-index $start_file $end_file${NC}"
git diff --ignore-space-at-eol --no-index "$start_file" "$end_file"
