#!/usr/bin/env bash

set -e

if [ $# -ne 3 ]; then
    echo "Usage: $0 <pattern> <start> <end>"
    echo "eg: $0 '**.go' startcommit endcommit"
    exit 1
fi

pattern="$1"
start="$2"
end="$3"

cwd="$(pwd)"

current_branch=$(git rev-parse --abbrev-ref HEAD)

temp_dir=$(mktemp -d)
if [ ! -e ${temp_dir} ]; then
    echo "Failed to create temporary directory."
    exit 1
fi

changed=$(git diff --name-only "$start..$end" -- "$pattern" || true)

if [ -z "$changed" ]; then
    echo "No changes detected"
    exit 0
fi

git checkout "$start" >/dev/null 2>&1
files_start=$(git ls-files "$pattern")
if [ -z "$files_start" ]; then
    mkdir -p "${temp_dir}/$start"
else
    dstll write $files_start -o "${temp_dir}/$start" -q
fi

git checkout "$end" >/dev/null 2>&1
files_end=$(git ls-files "$pattern")
if [ -z "$files_end" ]; then
    mkdir -p "${temp_dir}/$end"
else
    dstll write $files_end -o "${temp_dir}/$end" -q
fi

git checkout $current_branch >/dev/null

cd $temp_dir
changed_dstlled=$(git diff --name-only --no-index --relative "$start" "$end" || true)

if [ -z "$changed_dstlled" ]; then
    echo "No changes detected"
    exit 0
fi

git --no-pager diff --no-index --relative --unified=0 "$start" "$end" || true
