#!/usr/bin/env bash

selected_keys=$(
    tash ls |
        fzf \
            --multi \
            --reverse \
            --preview 'tash get {}' \
            --preview-window=right:70% \
            --preview-border=vertical \
            --border=none |
        xargs
)

if [ -z "$selected_keys" ]; then
    exit 0
fi

tash d ${selected_keys}
