#!/usr/bin/env bash

POPUP_BORDER_COLOR=#928374 # gruvbox gray darker

/opt/homebrew/bin/tmux \
    display-popup \
    -h 60% -w 100% \
    -y 50% \
    -S fg=$POPUP_BORDER_COLOR \
    -E \
    'shfl -s ~/.tsw'
