#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "No argument provided. Please provide a number between 1 and 5."
    exit 1
fi

if ! [[ "$1" =~ ^[1-9]$ ]]; then
    echo "Invalid argument. Please provide a number between 1 and 5."
    exit 1
fi

sessions=$(cat ~/.tsw)

if [ -z "$sessions" ]; then
    exit 1
fi

position=${1}
session=$(echo "$sessions" | sed -n "${position}p")
# session=$(/opt/homebrew/bin/tmux list-sessions -F "#{session_last_attached} #{session_name}" | sort -nr | awk '{print $2}' | sed -n "${position}p")

/opt/homebrew/bin/tmux switch-client -t "$session"
