#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "No argument provided. Please provide a number between 1 and 5."
    exit 1
fi

if ! [[ "$1" =~ ^[1-5]$ ]]; then
    echo "Invalid argument. Please provide a number between 1 and 5."
    exit 1
fi

sessions=$(cat ~/.tsw)

if [ -z "$sessions" ]; then
    exit 1
fi

session=$(echo "$sessions" | sed -n "${1}p")

/opt/homebrew/bin/tmux switch-client -t "$session"
