#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "No argument provided. Please provide a number between 1 and 5."
    exit 1
fi

if ! [[ "$1" =~ ^[1-5]$ ]]; then
    echo "Invalid argument. Please provide a number between 1 and 5."
    exit 1
fi

sessions=$(cat ~/.tsw)

if [ -z "$sessions" ]; then
    exit 1
fi

position=${1}
client_name=${2:-}
session=$(echo "$sessions" | sed -n "${position}p")

if [ -n "$client_name" ]; then
    tmux switch-client -c "$client_name" -t "$session"
else
    tmux switch-client -t "$session"
fi
