#!/usr/bin/env bash

if [ -z "${DIRS_TO_SEARCH:-}" ]; then
    printf 'DIRS_TO_SEARCH is not set\n' >&2
    exit 1
fi

txw() {
    local selected_entry
    local -a search_dirs

    IFS=':' read -r -a search_dirs <<<"$DIRS_TO_SEARCH"

    if [ -n "$1" ]; then
        selected_entry="$1"
    else
        selected_entry=$(fd . --max-depth=1 "${search_dirs[@]}" | fzf --multi --height=20 --layout=reverse --header="project?")
    fi

    if [ -n "$selected_entry" ]; then
        printf "%s\n" "$selected_entry" | while IFS= read -r project; do
            tmuxinator two-windows "$project"
        done
    fi
}

txw "$@"
