#!/usr/bin/env bash

export PROJECTS_DIR="$HOME/projects"
export WIKI_DIR="$HOME/projects/knowledge"
export CONFIG_DIR="$HOME/.config"
export GENERAL_PYTHON_ENV_NAME="general"

function txwpy() {
    # open tmuxinator in a specific work directory
    local selected_entry
    local selected_py_env

    if [ -n "$1" ]; then
        selected_py_env="$1"
    else
        selected_py_env=$(fd -t d --max-depth 1 --base-directory /Users/dhruvthakur/.virtualenvs | awk -F "/" '// {print $1}' | fzf --height=20 --layout=reverse --header="which python?")
    fi

    if [ -n "$2" ]; then
        selected_entry="$2"
    else
        selected_entry=$(fd . --max-depth=1 $PROJECTS_DIR $WORK_DIR $PROJECTS_DIR/rusttest | fzf --multi --height=20 --layout=reverse --header="project?")
    fi

    if [ -n "$selected_py_env" ]; then
        if [ -n "$selected_entry" ]; then
            printf "%s\n" "$selected_entry" | while IFS= read -r project; do
                tmuxinator two-windows $project $selected_py_env
            done
        fi
    fi
}

txwpy "$@"
