#!/usr/bin/env bash

set -euxo pipefail

bun install -g @anthropic-ai/claude-code @google/gemini-cli @sourcegraph/amp @github/copilot
cursor-agent upgrade

brew update && brew upgrade

cargo install-update -a
