#!/usr/bin/env bash

set -euxo pipefail

bun install -g @anthropic-ai/claude-code @sourcegraph/amp @mariozechner/pi-coding-agent
# cursor-agent upgrade

brew update && brew upgrade

cargo install-update -a
